from typing import Any, Dict, List
from app.models.entities import ScanFindingEntity, ThreatScanEntity

class BriefingEngine:
    @classmethod
    def generate_briefing(cls, title: str, target_date: str, scan: ThreatScanEntity, findings: List[ScanFindingEntity], created_by: str) -> Dict[str, Any]:
        tot = len(findings)
        crit = sum(1 for f in findings if f.priority_tier == 'CRITICAL')
        high = sum(1 for f in findings if f.priority_tier == 'HIGH')
        med = sum(1 for f in findings if f.priority_tier == 'MEDIUM')
        low = sum(1 for f in findings if f.priority_tier == 'LOW')
        kev = sum(1 for f in findings if f.is_cisa_kev)
        exp = sum(1 for f in findings if f.internet_exposed)
        avg = round(sum(f.composite_risk_score for f in findings) / tot, 1) if tot > 0 else 0.0
        stats = {'total_findings': tot, 'critical_count': crit, 'high_count': high, 'medium_count': med, 'low_count': low, 'cisa_kev_active_count': kev, 'internet_exposed_count': exp, 'average_composite_score': avg, 'scanned_assets_count': scan.scanned_assets_count, 'scan_title': scan.title, 'scan_id': scan.id}
        status = 'ELEVATED RISK POSTURE' if crit > 0 or kev > 0 else 'MODERATE RISK POSTURE' if high > 0 else 'CONTROLLED RISK POSTURE'
        urg = 'requires immediate 24-hour containment.' if status == 'ELEVATED RISK POSTURE' else 'warrants prioritized remediation within 7-day SLA.' if status == 'MODERATE RISK POSTURE' else 'exhibits baseline controls.'
        exec_sum = f"Security Intelligence Briefing for {target_date} ({status}). Analysis of scan '{scan.title}' evaluated {scan.scanned_assets_count} assets and identified {tot} confirmed correlations: {crit} CRITICAL, {high} HIGH, {med} MEDIUM. {exp} internet-facing, {kev} CISA KEV. Score {avg}/100. Operational response {urg}"
        sf = sorted(findings, key=lambda x: x.composite_risk_score, reverse=True)
        top = [{'cve_id': f.cve_id, 'asset_name': f.asset_name, 'asset_component': f.asset_component, 'asset_version': f.asset_version, 'composite_risk_score': f.composite_risk_score, 'priority_tier': f.priority_tier, 'cvss_score': f.cvss_score, 'epss_score': f.epss_score, 'is_cisa_kev': f.is_cisa_kev, 'internet_exposed': f.internet_exposed, 'match_reason': f.match_reason, 'remediation': f.remediation_recommendation} for f in sf[:5]]
        pb = [{'phase': 'containment', 'title': f'Immediate Isolation: {f.cve_id} on {f.asset_name}', 'description': f'Isolate ingress rule for {f.asset_component} on {f.asset_name}.' if f.internet_exposed else f'Restrict lateral traffic on host {f.asset_name}.', 'target_asset': f.asset_name, 'target_cve': f.cve_id} for f in [x for x in sf if x.priority_tier in ('CRITICAL', 'HIGH')][:3]]
        pb += [{'phase': 'remediation', 'title': f'Patch Application: {f.asset_component} ({f.cve_id})', 'description': f.remediation_recommendation, 'target_asset': f.asset_name, 'target_cve': f.cve_id} for f in sf[:5]]
        pb += [{'phase': 'verification', 'title': 'Post-Remediation Rescan', 'description': 'Trigger automated correlation scan to ensure affected version signatures no longer match.', 'target_asset': 'All correlated assets', 'target_cve': 'All active CVEs'}, {'phase': 'verification', 'title': 'Audit Review', 'description': 'Cross-reference connection logs against catalog IOCs.', 'target_asset': 'SOC', 'target_cve': 'Catalog IOCs'}]
        return {'title': title, 'target_date': target_date, 'scan_id': scan.id, 'summary_stats': stats, 'executive_summary': exec_sum, 'top_threats': top, 'mitigation_playbook': pb, 'created_by': created_by}

    @classmethod
    def render_markdown(cls, b: Dict[str, Any]) -> str:
        s = b.get('summary_stats', {})
        md = [f"# {b.get('title', 'Briefing')}", f"**Target Date:** {b.get('target_date', 'Today')} | **Generated By:** {b.get('created_by', 'Threat Engine')}\n", '## 1. Executive Summary', f"{b.get('executive_summary', '')}\n", '## 2. Key Metrics & Exposure Snapshot', f"- **Total Vulnerability Matches:** {s.get('total_findings', 0)}", f"- **Critical Severity Findings:** {s.get('critical_count', 0)}", f"- **High Severity Findings:** {s.get('high_count', 0)}", f"- **CISA Known Exploited (KEV):** {s.get('cisa_kev_active_count', 0)}", f"- **Internet-Exposed Assets:** {s.get('internet_exposed_count', 0)}", f"- **Composite Risk Index:** {s.get('average_composite_score', 0)} / 100\n", '## 3. Prioritized Threat Matrix (Top Exposures)', '| Priority | CVE ID | Asset | Component | Version | Composite Score | Action |', '|---|---|---|---|---|---|---|']
        for t in b.get('top_threats', []):
            md.append(f"| **{t['priority_tier']}** | `{t['cve_id']}` | {t['asset_name']} | `{t['asset_component']}` | {t['asset_version']} | {t['composite_risk_score']}/100 | {t['remediation']} |")
        md.append('\n## 4. Actionable Remediation Playbook')
        for it in b.get('mitigation_playbook', []):
            md.extend([f"### [{it['phase'].upper()}] {it['title']}", f"- **Target Asset:** {it['target_asset']}", f"- **Reference CVE:** {it['target_cve']}", f"- **Action:** {it['description']}\n"])
        if b.get('advisory_narrative'):
            md.extend(['\n## 5. Advisory Narrative (Opt-In AI Evaluation)', f"> [!NOTE] {b.get('advisory_disclaimer', 'Advisory notice')}\n", b['advisory_narrative']])
        md.append('\n---\n*Threat Intel Analyzer by Alan Vo (alanvo@gmail.com)*')
        return '\n'.join(md)
